SAMKING25/TFG-SAMAS-home

index.php
Política de cookies: Se abre en una nueva pestaña
=> Política de cookies: Se abre en una nueva pestaña

login/proveedor/iniciar_sesion_proveedor.php, login/proveedor/registro_proveedor.php, login/usuario/iniciar_sesion_usuario.php, login/usuario/registro_usuario.php
Validación login con JavaScript
=> Validación login con JavaScript

contacto/index.php, css/landing.css, index.php, login/proveedor/cambiar_credenciales_proveedor.php, login/proveedor/iniciar_sesion_proveedor.php, login/proveedor/registro_proveedor.php, login/usuario/cambiar_credenciales_usuario.php, login/usuario/iniciar_sesion_usuario.php, login/usuario/registro_usuario.php, navbar.php, panel-control/index.php, panel-control/layout/header.php, panel-control/layout/sidebar.php, panel-control/productos/editar_producto.php, panel-control/productos/index.php, panel-control/productos/nuevo_producto.php, panel-control/productos/ver_producto.php, pasarela-pago/completado.html, pasarela-pago/index.php, plano/index.php, suscripcion/index.php
=> Formato a todos los archivos

panel-control/productos/editar_producto.php, util/bd/samashome_script.sql
Boton cancelar -> Salir / Nuevo script bd
=> Boton cancelar -> Salir / Nuevo script bd

contacto/index.php
falta que tenga todos los datos rellenos para que puedas enviar
=> validacion contacto 

login/usuario/registro_usuario.php, util/bd/samashome_script.sql
=> Registro usuario arreglado

carrito/index.php, index.php, login/proveedor/iniciar_sesion_proveedor.php, login/usuario/iniciar_sesion_usuario.php, navbar.php, panel-control/index.php, panel-control/layout/header.php, panel-control/productos/editar_producto.php, panel-control/productos/index.php, panel-control/productos/nuevo_producto.php, panel-control/productos/ver_producto.php
Diferenciación de empresa o usuario implementada
=> Diferenciación de empresa o usuario implementada

.htaccess, index.php, login/proveedor/cambiar_credenciales_proveedor.php, navbar.php, panel-control/layout/sidebar.php, productos/index.php, util/error.php
Sistema de enrutamiento añadido (URLs bonitas, no acceso a archivos, errores personalizados)
=> Sistema de enrutamiento añadido (URLs bonitas, no acceso a archivos, errores personalizados)

carrito/index.php
=> Plantilla carrito lista

contacto/index.php, index.php, productos/index.php
Posición bot IA corregido / Menú despegable arreglado en contacto y productos
=> Posición bot IA corregido / Menú despegable arreglado en contacto y productos

contacto/index.php, index.php, login/usuario/iniciar_sesion_usuario.php, login/usuario/registro_usuario.php, navbar.php, panel-control/layout/header.php, panel-control/layout/sidebar.php, panel-control/productos/editar_producto.php, productos/ver_producto.php, suscripcion/index.php, util/funciones/cerrar_sesion.php
Rutas actualizadas sin .php / Validación JavaScript contacto
=> Rutas actualizadas sin .php / Validación JavaScript contacto

login/proveedor/iniciar_sesion_proveedor.php, plano/JS/funcionalidades.js
Rutas actualizadas sin .php_2 / Elimina productos del plano sin confirmación
=> Rutas actualizadas sin .php_2 / Elimina productos del plano sin confirmación

contacto/index.php
=> datos.php --> datos

plano/JS/funcionalidades.js, plano/index.php, util/bd/samashome_script.sql
Plano: colores scroll semi-corregido, colores cambiados, altura de pared cambiada
=> Plano: colores scroll semi-corregido, colores cambiados, altura de pared cambiada

plano/JS/funcionalidades.js, plano/index.php
=> Plano: Mejoras significativas

plano/JS/Limpiofunc.js, plano/JS/PorSi.js, plano/PorSi.php
Plano: Botón Ratón/Mover, Importar JSON, Zoom ajustado, Límite de canva
=> Plano: Botón Ratón/Mover, Importar JSON, Zoom ajustado, Límite de canva

plano/JS/funcionalidades.js, plano/index.php
Plano: Restaurar zoom, Copia/Pegar semihecho
=> Plano: Restaurar zoom, Copia/Pegar semihecho

pasarela-pago/index.php
=> pasarela de pago centrada

panel-control/layout/sidebar.php
Corregido active en el sidebar panel-control
=> Corregido active en el sidebar panel-control

navbar.php, productos/index.php
icono de busqueda cambiado en navbar
=> icono de busqueda cambiado en navbar

util/bd/samashome_script.sql
=> Script BD actualizado

login/usuario/registro_usuario.php, login/usuario/verificar_codigo.php
=> Login: Verificación de correo

carrito/index.php
Carrito: Script bootstrap corregido
=> Carrito: Script bootstrap corregido

udify-bot.php
=> Bot IA z-index corregido

login/proveedor/iniciar_sesion_proveedor.php, login/proveedor/registro_proveedor.php, login/usuario/iniciar_sesion_usuario.php, login/usuario/registro_usuario.php
=> Validación login corregida

login/proveedor/iniciar_sesion_proveedor.php, login/usuario/iniciar_sesion_usuario.php
Login: error 'El correo y la contraseña no coindicen' implementado
=> Login: error 'El correo y la contraseña no coindicen' implementado

login/proveedor/iniciar_sesion_proveedor.php, login/usuario/iniciar_sesion_usuario.php
Login: error 'El correo y la contraseña no coinciden' implementado
=> Login: error 'El correo y la contraseña no coinciden' implementado

footer.php
Footer: ajustado al tamaño de cada dispositivo_2
=> Footer: ajustado al tamaño de cada dispositivo_2

plano/JS/funcionalidades.js, plano/index.php
Plano: sale total carrito, y cantidad borra y vuelve a poner (Casi perfecto)
=> Plano: sale total carrito, y cantidad borra y vuelve a poner (Casi perfecto)

css/landing.css, plano/JS/funcionalidades.js
=> Letras color blanco arreglado

contacto/index.php, footer.php, index.php, plano/index.php, productos/ver_producto.php
Plano: vista detalle / Footer: cambio de botones dependiendo si proveedor ? usuario
=> Plano: vista detalle / Footer: cambio de botones dependiendo si proveedor ? usuario

css/landing.css, plano/index.php
=> Restaurado estilos de Navbar

css/landing.css, index.php, productos/index.php
Landing: Productos nuevos - nuevo diseño / Productos: Hover imagen
=> Landing: Productos nuevos - nuevo diseño / Productos: Hover imagen

panel-control/index.php, panel-control/layout/header.php, panel-control/layout/sidebar.php, panel-control/productos/editar_producto.php, panel-control/productos/index.php, panel-control/productos/nuevo_producto.php, panel-control/productos/ver_producto.php
Panel de control: estilo renovado
=> Panel de control: estilo renovado

login/proveedor/cambiar_credenciales_proveedor.php, login/usuario/cambiar_credenciales_usuario.php, navbar.php, panel-control/layout/header.php, panel-control/layout/sidebar.php, panel-control/productos/ver_producto.php
Panel de control: estilo mejorado más / Ajustes de perfil: estilo mejorado
=> Panel de control: estilo mejorado más / Ajustes de perfil: estilo mejorado

carrito/index.php, navbar.php, productos/index.php, productos/ver_producto.php
Productos/Carrito: nuevo diseño
=> Productos/Carrito: nuevo diseño

carrito/index.php, contacto/datos.php, index.php, login/proveedor/cambiar_credenciales_proveedor.php, login/proveedor/registro_proveedor.php, login/usuario/cambiar_credenciales_usuario.php, login/usuario/iniciar_sesion_usuario.php, navbar.php, panel-control/index.php, panel-control/layout/sidebar.php, panel-control/productos/editar_producto.php, panel-control/productos/nuevo_producto.php, panel-control/productos/ver_producto.php, pasarela-pago/index.php, pedidos/index.php, pedidos/tramitar-pedido.php, pedidos/ver_pedido.php, plano/PorSi.php, productos/index.php, productos/ver_producto.php, suscripcion/cancelar.php, suscripcion/index.php
.php eliminados de todos los archivos
=> .php eliminados de todos los archivos

contacto/datos.php, productos/index.php, util/bd/samashome_script.sql
.php/.html eliminados de todos los archivos
=> .php/.html eliminados de todos los archivos

login/proveedor/iniciar_sesion_proveedor.php, login/proveedor/registro_proveedor.php, login/usuario/iniciar_sesion_usuario.php, login/usuario/verificar_codigo.php
Login: corregido mensaje de verificado
=> Login: corregido mensaje de verificado

footer.php, navbar.php, plano/confirmacion_plano.php, util/bd/samashome_script.sql
Plano: corregido SALIR del plano_1
=> Plano: corregido SALIR del plano_1

login/usuario/registro_usuario.php
Login: diseño de correo de verificación
=> Login: diseño de correo de verificación

panel-control/productos/editar_producto.php, panel-control/productos/nuevo_producto.php
=> Rutas arregladas

plano/JS/funcionalidades.js
=> Plano comentado
